entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  cloudflare:
    acme:
      email: pasha04072004@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    jenkins:
      rule: "Host(`jenkins.mydom.com`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: jenkins

log:
  level: DEBUG